[package]
name = "tauri-plugin-printer"
version = "1.2.0"
authors = [ "47vigen" ]
description = ""
license = ""
repository = ""
edition = "2021"
exclude = ["/examples", "/webview-dist", "/webview-src", "node_modules"]

[dependencies]
tauri = { version = "2.0.0-alpha" }
base64 = "0.21.2"
